feat: option to keep files no toc inside untouched
thlorenz/doctoc pull request #181
Opened 2020-07-03 01:59 UTC by uetchy

add cli flag to prevent doctoc from adding toc to a file without toc.
this is good for CI or the combination with [`lint-staged`](https://github.com/okonet/lint-staged).
with -p, doctoc will update toc if md has toc sectioon, otherwise doctoc keep it unmodified.

I'm not sure `preserve` is the right name for it. so please change it if you have a better choice.

2020-10-12 21:31 UTC, AndrewSouthpaw requested changes
I'd add some additional printout, clarifying that only existing TOC'ed files will be updated. Maybe [here](https://github.com/thlorenz/doctoc/pull/181/files#diff-deb40c96c1eed97349c7c1ad0c1f31c9R43-R44).

Also, I'd suggest a name like `--update-existing` or `--update-only` as that may carry more meaning than "preserve".

Thoughts?

2020-10-14 09:26 UTC, uetchy commented
@AndrewSouthpaw Thank you for the suggestion. `--update-only` sounds nice.
Also, I've added the notice and help text for this option.

2020-10-14 16:50 UTC, AndrewSouthpaw requested changes
Looks great! Just one minor word tweak.

2020-10-14 16:50 UTC, AndrewSouthpaw commented on doctoc.js
> +    console.log('--update-only flag is enabled. Only updating existing TOC.')
Nit: "... Only updating files that already have a TOC." I think that reads more clearly.

2020-10-15 11:28 UTC, uetchy commented on doctoc.js
> +    console.log('--update-only flag is enabled. Only updating existing TOC.')
```suggestion
    console.log('--update-only flag is enabled. Only updating files that already have a TOC.')
```

@AndrewSouthpaw Now sounds concise!

2020-10-22 20:56 UTC, AndrewSouthpaw approved these changes
Thanks for your contribution!

2020-10-22 20:56 UTC, merged