Add support for custom "Don't edit" message
thlorenz/doctoc pull request #192
Opened 2021-03-13 05:37 UTC by tpansino

# Pull Request

## Description of Changes

- Added support for customizing the `DON'T EDIT THIS SECTION` message (useful for changing the message if using this tool via something like `pre-commit`).

2021-03-22 19:44 UTC, AndrewSouthpaw requested changes
Great start! Please add some tests to assert the default and new behavior and I think this is ready to go. 🚢

2021-04-09 16:58 UTC, countryboy20031 approved these changes

2021-04-09 23:09 UTC, countryboy20031 approved these changes

2021-04-20 19:24 UTC, AndrewSouthpaw commented
@countryboy20031 or @tpansino if one of you is willing to add tests here, I'm happy to get this merged. 😄

2024-10-12 22:39 UTC, closed without merging